# Generated by Django 5.2.4 on 2025-07-23 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_activated_invite_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_invite_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
