services:
  web:
    image: suetosha/referral_system:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - ENGINE=django.db.backends.postgresql
      - NAME=postgres
      - USER=postgres
      - PASSWORD=postgres
      - HOST=db
      - PORT=5432

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: